"""Text output routines for lamprop."""
from typing import List
import pandas as pd
from ..core.utils import is_ortho, is_ti, to_abaqus_i

def text_output(lam, eng: bool = True, mat: bool = True, fea: bool = True) -> List[str]:
    """Return the output as a list of lines."""
    lines = [
        "** Generated by lamprop",
        f"** laminate: {lam.name}",
        f"** thickness: {lam.thickness:.2f} mm, density: {lam.rho:4.2f} g/cm³",
        f"** fiber volume fraction: {lam.vf*100:.3g}%, fiber weight fraction: {lam.wf*100:.3g}%",
        f"** laminate weight: {lam.fiber_weight + lam.resin_weight:.0f} g/m², resin consumption: {lam.resin_weight:.0f} g/m²",
        "** num weight angle   vf fiber",
        "**     [g/m²]   [°]  [%]",
    ]
    ln = 1
    for la in lam.layers:
        if isinstance(la, str):
            lines.append(f"** {la}")
            continue
        lines.append(
            f"** {ln:3} {la.fiber_weight:6g} {la.angle:5g} {la.vf * 100:4.3g} {la.fiber.name}"
        )
        ln += 1
    if eng:
        lines += [f"** {line}" for line in _engprop(lam)]
    if mat:
        lines += [f"** {line}" for line in _matrices(lam)]
    if fea:
        lines += _fea(lam)
    lines.append("**")
    return lines

def _engprop(l) -> List[str]:
    """Return engineering properties as text."""
    lines = ["In-plane engineering properties:"]
    lines += [
        f"E_x  = {l.Ex:.0f} MPa, E_y  = {l.Ey:.0f} MPa, E_z  = {l.Ez:.0f} MPa ",
        f"G_xy  = {l.Gxy:.0f} MPa, G_xz  = {l.Gxz:.0f} MPa, G_yz  = {l.Gyz:.0f} MPa ",
        f"nu_xy = {l.nu_xy:7.5f}",
        f"alpha_x = {l.alpha_x:9.4g} K⁻¹, alpha_y = {l.alpha_y:9.4g} K⁻¹",
    ]
    lines.append("Engineering properties derived from 3D stiffness matrix:")
    lines.append(f"E_x = {l.tEx:.0f} MPa, E_y = {l.tEy:.0f} MPa, E_z = {l.tEz:.0f} MPa")
    lines.append(
        f"G_xy = {l.tGxy:.0f} MPa, G_xz = {l.tGxz:.0f} MPa, G_yz = {l.tGyz:.0f} MPa"
    )
    lines.append(f"nu_xy = {l.t_nu_xy:.3f}, nu_xz = {l.t_nu_xz:.3f}, nu_yz = {l.t_nu_yz:.3f}")
    return lines

def _matrices(l) -> List[str]:
    """Return matrices as text using pandas."""
    lines = ["In-plane stiffness (ABD) matrix:"]
    df_abd = pd.DataFrame(l.ABD)
    lines += df_abd.to_string().split('\n')
    lines.append("Transverse (H) stiffness matrix:")
    df_h = pd.DataFrame(l.H)
    lines += df_h.to_string().split('\n')
    lines += ["3D stiffness tensor [C], contracted notation:"]
    lines.append("(indices for stress/strain are in the order 11, 22, 33, 23, 13, 12)")
    df_c = pd.DataFrame(l.C)
    lines += df_c.to_string().split('\n')
    return lines

def _fea(l) -> List[str]:
    """Return FEA material data."""
    lines = ["** Material data for CalculiX / Abaqus (SI units):"]
    D = to_abaqus_i(l.C)
    lines.append(f"*MATERIAL,NAME={l.name}")
    if is_ortho(l.C):
        lines.append("*ELASTIC,TYPE=ORTHO")
        lines.append(
            f"{D[0,0]:.4g},{D[0,1]:.4g},{D[1,1]:.4g},"
            f"{D[0,2]:.4g},{D[1,2]:.4g},{D[2,2]:.4g},"
            f"{D[3,3]:.4g},{D[4,4]:.4g},"
        )
        lines.append(f"{D[5,5]:.4g},293")
    else:
        lines.append("*ELASTIC,TYPE=ANISO")
        lines.append(
            f"{D[0,0]:.4g},{D[0,1]:.4g},{D[1,1]:.4g},"
            f"{D[0,2]:.4g},{D[1,2]:.4g},{D[2,2]:.4g},"
            f"{D[0,3]:.4g},{D[1,3]:.4g},"
        )
        lines.append(
            f"{D[2,3]:.4g},{D[3,3]:.4g},{D[0,4]:.4g},"
            f"{D[1,4]:.4g},{D[2,4]:.4g},{D[3,4]:.4g},"
            f"{D[4,4]:.4g},{D[0,5]:.4g},"
        )
        lines.append(
            f"{D[1,5]:.4g},{D[2,5]:.4g},{D[3,5]:.4g},"
            f"{D[4,5]:.4g},{D[5,5]:.4g},293"
        )
    lines.append("*DENSITY")
    lines.append(f"{l.rho*1000:.0f}")
    return lines
